## Regression-- Estimation of conditional mean
dataUsed1=read.csv("C:\\tips.csv")
head(dataUsed1)
tail(dataUsed1)

##===Case 1
Eq1=as.formula("tip~total_bill")
output_1A=lm(Eq1,data=dataUsed1)
summary(output_1A)
names(summary(output_1A))

#Learning Point 1: Interpretation of parameter estimates
summary(output_1A)$coef

#Learning Point 2: Diagnosis of residuals by 4 plots
dev.new()
par(mfrow=c(2,2))
plot(output_1A, which=c(1:3,5))
par(mfrow=c(1,1))


#Learning Point 3: How to evaluate the performance of prediction?
## plot 樣本迴歸圖 method 1.
Pred=predict(output_1A, interval="confidence") # predict(output1) is simpler
dev.new()
with(plot(tip~total_bill),data=dataUsed1)
abline(output_1A,col="blue")
with(lines(Pred[,"lwr"] ~ total_bill, lwd=0.05, lty=4, col=2),data=dataUsed1)
with(lines(Pred[,"upr"] ~ total_bill, lwd=0.05, lty=4, col=2),data=dataUsed1)
legend("topleft", c("regression line", "low", "upper"), lty=c(1,4,4), lwd=0.05, bty="n")

## plot 樣本迴歸圖 method 2.
library(ggplot2)
library(dplyr)
dataUsed1 %>%
  ggplot(aes(x=total_bill, y=tip)) + #label=Species
  #geom_line(color="red") + #color="red"
  geom_point(shape=20, color="black", fill="#69b3a2", size=1) + #
  geom_smooth(color="blue",method = "lm")+
  ggtitle("散佈圖")


Y=dataUsed1$tip
EY=predict(output_1A)
Performance=forecast::accuracy(Y,EY)
Performance[,c("RMSE","MAE","MAPE")]

Error=output_1A$residuals
sqrt(mean(Error^2))
mean(abs(Error))
mean(abs(Error/EY))

##===Case 2 
Eq2=as.formula("tip ~ total_bill + time")
output_1B=lm(Eq2,data=dataUsed1)
summary(output_1B)$coef

EY2=predict(output_1B)
Y=dataUsed1$tip
Performance=forecast::accuracy(Y,EY2)
Performance[,c("RMSE","MAE","MAPE")]

## Diagnosis of residuals by 4 plots
dev.new()
par(mfrow=c(2,2))
plot(output_1B, which=c(1:3,5))
par(mfrow=c(1,1))

#problem 2
Eq3=as.formula("tip ~ total_bill + day")
output_1C=lm(Eq3,data=dataUsed1)
summary(output_1C)$coef

EY3=predict(output_1C)
Performance=forecast::accuracy(Y,EY3)
Performance[,c("RMSE","MAE","MAPE")]

## R tip. Save output coefficient table
coef_output_1A=summary(output_1A)$coef
write.csv(coef_output_1A,file="C:\\coef_output_1A.csv")

#Note. You may also save this table 
papeR::prettify(summary(output_1A), confint = FALSE)

p=papeR::prettify(summary(output_1A), confint = FALSE)
write.csv(p,file="C:\\p.csv")

# 資料存在異質變異 Since we know the IID assumption no longer holds, we need the package "sandwich" to construct new estimators
library(sandwich)
white=vcovHC(output_1B, type="HC0")    # ("HC0","HC1","HC2","HC3","HC4","HC4m”, “HC5”)
library(lmtest)
coeftest(output_1B,vcov= white)    # Ecker-White estimator
vcovHC(output_1B)                  # the Ecker-White covariance matrix

### Problem 1. Compare the prediction performance of output_1A with output_1B

### Problem 2. Interpretation of estimates generated by Eq=as.formula("tip~total_bill+day")

### Problem 3. Explain the 4 plots of output_1B
